### ISSUE TITLE
[Question] Doesn't pink noise need to be reset?

### ISSUE THREAD

**Issue by qgallouedec** [martius-lab/pink-noise-rl#2]
Hi, I'm now delving a little deeper into your paper and its implementation. Unlike OU noise, pink noise doesn't implement a reset. At first glance, it's not clear to me why. Shouldn't noise be reset at the start of each episode?

**Comment by jkbjh** [comment]
When you check the paper, Appendix A.1 (Figure A.3), you can see that the action distribution for colored noise at the first time step is the same as for each other time step. This is different to OU, where the distribution changes a lot. (Perhaps OU should be given some burn-in time, but as far as I know, this does not happen in e.g., SB3). Judging from this, there is a larger difference between resetting/not-resetting OU, than there is for colored/pink noise.

In this code, the colored noise is pre-generated for a certain number of steps, so there could be a "jump" when this pre-generated sequence is exhausted and the next sequence has to be re-generated. This _could_ create a small artefact in the expected power spectral density; However, when the generated sequence is long, this would happen rarely, and thus the impact of this _should_ be negligibly small. If your environment is unlikely to terminate at exactly the same time step, relative to the generator, each time, then this will probably vanish in the noise.

**Comment by qgallouedec** [comment]
Thanks for your reply.

> However, when the generated sequence is long, this would happen rarely, and thus the impact of this should be negligibly small.

Given the way it's implemented (`seq_len = env._max_episode_steps`), it seems to me that it's rather the opposite case that occurs, the generated noise is use for several episodes. 
For example, with pendulum, for which max_episode_steps is 500, but a "bad" policy typically gets episodes around 20 interactions, we get a noise that is generated for around 500/20=25 episodes, right?

**Comment by jkbjh** [comment]
Interesting point; I think that it's _probably_ not a problem:

1. asymptotically (in the number of rollouts) it does not matter: if you collect many rollouts, the starting action will be Gaussian distributed and the following actions will have the same distribution, as you would get if you would do a reset. (extrapolating from Figure A.3) 

2. If you do _very few_ rollouts and have a _very correlated_ noise, you would be more likely to start in the same range of actions as before; i.e.,  your noise is so correlated it would only move slowly from one extreme to the other. (Which is _probably_ too correlated to be useful for your problem.) In this case, you would probably see a less evenly spread out distribution in the action noise compared to when you do the resets and it might be beneficial to do the resets, but using a less correlated noise will probably be more effective.

If you do some experiments, let us know :-)

**Comment by qgallouedec** [comment]
For the record, I've done some experiments with Hopper. Episode lengths typically ranged from 20 to 500. The results seem to show that resetting at the beginning of each episode has no significant impact.
![W B Chart 12_19_2023, 4 16 03 PM](https://github.com/martius-lab/pink-noise-rl/assets/45557362/be87c72a-c464-46bd-a4e1-55349f87db64)

**Comment by jkbjh** [comment]
nice, thanks!

**Comment by qgallouedec** [comment]
Closing as the initial question has been answered. Thanks @jkbjh
